name: Lint Files

on:
  push:
    branches-ignore:
      - main
      # - dev

jobs:
  lint-my-portfolio:
    name: Lint My-Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Use NodeJS v22.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0
      - name: Install Dependencies
        run: |
          cd my-portfolio
          npm install
      - name: Lint
        run: |
          cd my-portfolio
          npm run lint